// @ts-expect-error - No types generated by vercel
import { VERCEL_URL } from "$env/static/private";
import type { LayoutServerLoad } from "./$types";

export const load: LayoutServerLoad = () => {
  return {
    vercelUrl: VERCEL_URL,
  };
};
